"""add admin moderation fields to playlists

Revision ID: a12c82b440c3
Revises: ca95020e6813
Create Date: 2026-02-08 19:44:23.352679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a12c82b440c3'
down_revision: Union[str, Sequence[str], None] = 'ca95020e6813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('is_locked', sa.Boolean(), nullable=False))
    op.add_column('playlists', sa.Column('locked_by', sa.UUID(), nullable=True))
    op.add_column('playlists', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'playlists', 'users', ['locked_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'playlists', type_='foreignkey')
    op.drop_column('playlists', 'locked_at')
    op.drop_column('playlists', 'locked_by')
    op.drop_column('playlists', 'is_locked')
    # ### end Alembic commands ###
