import { useState } from "react";

const AiDiscovery = () => {
  const [prompt, setPrompt] = useState("");
  const [loading, setLoading] = useState(false);
  const [suggestions, setSuggestions] = useState([]);

  const askAi = () => {
    setLoading(true);

    // 🔮 MOCK AI RESPONSE (for visualization)
    setTimeout(() => {
      setSuggestions([
        "Lo-Fi Coding Beats",
        "Deep Focus Instrumentals",
        "Late Night Chillhop",
        "Minimal Techno Flow",
      ]);
      setLoading(false);
    }, 1200);
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold">
          🤖 AI Music Discovery
        </h1>
        <p className="text-gray-400 mt-2">
          Tell me your mood and I’ll find the perfect music for you.
        </p>
      </div>

      {/* Prompt Box */}
      <div className="bg-zinc-800 rounded-xl p-6 space-y-4">
        <textarea
          placeholder="Example: Chill music for late-night coding..."
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="w-full h-24 p-4 rounded-lg bg-zinc-900 text-white outline-none resize-none"
        />

        <button
          onClick={askAi}
          disabled={!prompt || loading}
          className="bg-green-500 text-black px-6 py-2 rounded-lg font-semibold hover:bg-green-400 disabled:opacity-50"
        >
          {loading ? "Thinking..." : "Discover Music"}
        </button>
      </div>

      {/* AI Suggestions */}
      {suggestions.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-xl font-semibold">
            🎧 AI Suggestions for you
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {suggestions.map((item, index) => (
              <div
                key={index}
                className="bg-zinc-800 p-4 rounded-xl hover:bg-zinc-700 transition cursor-pointer"
              >
                <h3 className="font-semibold">{item}</h3>
                <p className="text-sm text-gray-400">
                  Generated by AI based on your mood
                </p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};

export default AiDiscovery;
